Repository manab-kb/SDA-Project, pull requests merged in 2023-04, with the labels that each got.

#33 Syncing branches
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/measure/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: sync

#34 Distance measurement activity updates
  README.md
  app/src/main/java/com/example/measure/MainActivity2.kt
  app/src/main/res/layout/activity_main2.xml
  app/src/main/res/layout/activity_main4.xml
  app/src/main/res/layout/activity_main6.xml
  app/src/main/res/layout/activity_main7.xml
Labels: enhancement

#35 Subgroup 3
  app/src/main/java/com/example/measure/MainActivity3.kt
  app/src/main/res/layout/activity_main3.xml
  build.gradle
Labels: bug

#36 Branch Sync
  app/src/main/java/com/example/measure/MainActivity10.kt
Labels: sync

#38 Subgroup 1
  app/src/main/java/com/example/measure/MainActivity7.kt
  app/src/main/res/layout/activity_main7.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
Labels: bug

#43 Fixed bugs and removed unused dependencies
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/measure/MainActivity2.kt
Labels: bug, enhancement
